version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: mtbs
      POSTGRES_USER: mtbsuser
      POSTGRES_PASSWORD: mtbspass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init_cinema.sql:/docker-entrypoint-initdb.d/db_init_cinema.sql:ro
    networks:
      - mtbsnet

  movies-service:
    build:
      context: ./movies
    container_name: movies-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mtbs
      SPRING_DATASOURCE_USERNAME: mtbsuser
      SPRING_DATASOURCE_PASSWORD: mtbspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mtbsnet

  usermanagement-service:
    build:
      context: ./usermanagement
    container_name: usermanagement-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mtbs
      SPRING_DATASOURCE_USERNAME: mtbsuser
      SPRING_DATASOURCE_PASSWORD: mtbspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mtbsnet

volumes:
  pgdata:

networks:
  mtbsnet:
